app/departamento/urls.py
from django.contrib import admin
from django.urls import path


from . import views
app_name = 'departamento_app'
urlpatterns = [
  
    path('new-departamento/', views.newDepartamentoView.as_view(),name='new-departamento'),
    path('all-departamento/', views.ListAllDepartamentos.as_view(),name='all-departamento'),
    
 ]

app/personas/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'personas_app'
urlpatterns = [
  
    path('listar-all-personas/', views.ListAllPersonas.as_view(),name ='all-personas'),
    path('list-by-area/<area>/', views.ListByAreaPersonas.as_view(),name ='list-by-area'),
    path('find-personas/', views.ListPersonasByKeyword.as_view(),name ='find-personas'),
    path('habilidades/', views.ListHabilidades.as_view()),
    path('ver-detail/<pk>/', views.PersonasDetailView.as_view(),name='ver-detail'),
    path('add-personas/', views.PersonasCreateView.as_view(),name='add-personas'),
    path('success/', views.SuccesView.as_view(),name='success'),
    path('update-personas/<pk>/', views.PersonasUpdateView.as_view(),name='update-personas'),
    path('delete-personas/<pk>/', views.PersonasDeleteView.as_view(),name='delete-personas'),
    
   
 ]

empleados/urls.py
"""empleados URL Configuration

"""
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('',include('app.departamento.urls')),
    re_path('',include('app.personas.urls')),
    re_path('',include('app.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
<div class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="medium">
    <button class="menu-icon" type="button" data-toggle="responsive-menu"></button>
    <div class="title-bar-title">Menu</div>
  </div>
  
  <div class="top-bar" id="responsive-menu">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Empleados</li>
        <li class="has-submenu">
          <a href="{% url 'personas_app:all-personas' %}">Listar</a>
        
        </li>
        <li><a href="{% url 'departamento_app:all-departamento' %}">Departamentos</a></li>
        
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><input type="search" placeholder="Buscar Empleado"></li>
        <li><a type="button" class="button" href="{% url 'personas_app:add-personas' %}"">Registrar Nuevo</a></li>
      </ul>
    </div> 
  </div>

  