app/departamento/urls.py
from django.contrib import admin
from django.urls import path


from . import views
app_name = 'departamento_app'
urlpatterns = [
  
    path('new-departamento/', views.newDepartamentoView.as_view(),name='new-departamento'),
    path('all-departamento/', views.ListAllDepartamentos.as_view(),name='all-departamento'),
    
 ]

app/personas/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'personas_app'
urlpatterns = [
  
    path('listar-all-personas/', views.ListAllPersonas.as_view(),name ='all-personas'),
    path('list-by-area/<area>/', views.ListByAreaPersonas.as_view(),name ='list-by-area'),
    path('find-personas/', views.ListPersonasByKeyword.as_view(),name ='find-personas'),
    path('habilidades/', views.ListHabilidades.as_view()),
    path('ver-detail/<pk>/', views.PersonasDetailView.as_view(),name='ver-detail'),
    path('add-personas/', views.PersonasCreateView.as_view(),name='add-personas'),
    path('success/', views.SuccesView.as_view(),name='success'),
    path('update-personas/<pk>/', views.PersonasUpdateView.as_view(),name='update-personas'),
    path('delete-personas/<pk>/', views.PersonasDeleteView.as_view(),name='delete-personas'),
    
   
 ]

empleados/urls.py
"""empleados URL Configuration

"""
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('',include('app.departamento.urls')),
    re_path('',include('app.personas.urls')),
    re_path('',include('app.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/departamento/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name = models.CharField('Nombre',max_length=100)
    shor_name = models.CharField('Nombre Corto',max_length=50, unique=True)
    anulate = models.BooleanField('Anulada',default=False)


    class Meta:
        verbose_name= 'Departamento'
        verbose_name_plural='Dpto'
    def __str__(self):
        return str(self.id) + '-' + self.name + '-' + self.shor_name

app/departamento/forms.py
from django import forms


class NewDepartamentoForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shorname = forms.CharField(max_length=50)

   

app/departamento/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from .forms import NewDepartamentoForm
from app.personas.models import Habilidades, Personas
from app.departamento.models import Departamento
from django.views.generic import (
    ListView,)

class ListAllDepartamentos(ListView):
    template_name = 'departamento/all_departamento.html'
    #model = Personas
    paginate_by = 4
    ordering = ('name',)
    context_object_name = 'departamentos'
    def get_queryset(self):
        palabra_clave = self.request.GET.get('kword', '')
        lista = Departamento.objects.filter(
            name__icontains=palabra_clave
        )
        return lista




class newDepartamentoView(FormView):
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepartamentoForm
    success_url = reverse_lazy('personas_app:success')

    def form_valid(self, form):

        dpto=Departamento(
            name=form.cleaned_data['departamento'],
            shor_name=form.cleaned_data['shorname'],
        )
        dpto.save()
        nombre = form.cleaned_data['nombre']
        apellidos = form.cleaned_data['apellidos']
        Personas.objects.create(
            name=nombre,
            last_name=apellidos,
            departamento=dpto,
            job='1',
            salario=0,
            cv='',
            


        )
       
        return super(newDepartamentoView, self).form_valid(form)

templates/departamento/all_departamento.html
{% extends 'base.html' %}
{% load static%}
{% block title %} Sistema Empleado | All Departamentos {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}


<div class="grid-container">
    <div class="grid-x">
      <h1 class="cell">Lista Departamentos</h1>
      <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
        <div class="cell large-7">
          <input type="search" id="kword" name="kword" placeholder="Buscar Departamentos">
        </div>
  
        <div class="cell large-2">
          <button type="submit" class="success button">Buscar</button>
        </div>
        <div class="cell large-2">
          <a type="button" class="button" href="{% url 'departamento_app:new-departamento' %}">Nuevo Dpto</a>
        </div>
      </form>
  
  
      <div class="cell grid-x">
        <table>
          <thead>
            <tr>
              <th width="200">Gerencia</th>
              <th width="200">Departamento</th>
              <th width="150">Empleados</th>
            
            </tr>
          </thead>
          <tbody>
            {% for d in departamentos %}
            <tr>
              <td>{{ d.name }} </td>
              <td>{{ d.shor_name }} </td>
              
              <td><a class="button" href="{% url 'personas_app:list-by-area' d.shor_name %}" >Ver Empleados</a> </td>
            </tr>
            {% empty %}
            <li>No departamentos yet.</li>
            {% endfor %}
          </tbody>
        </table>
  
  
  
      </div>
      <div class="cell">
        {% if is_paginated %}
  
        <nav aria-label="Pagination">
          <ul class="pagination text-center">
            {% if page_obj.has_previous %}
            <li class="pagination-previous"><a href="?page={{page_obj.previous_page_number}}"
                aria-label="Next page">Previous</a></li>
            {% endif %}
  
            {% for pagina in paginator.page_range %}
            {% if page_obj.number == pagina %}
  
            <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }}</li>
  
            {% else %}
  
            <li><a href="?page={{pagina}}" aria-label="Page 2">{{ pagina }}</a></li>
            {% endif %}
            {% endfor %}
  
            {% if page_obj.has_next %}
            <li class="pagination-next"><a href="?page={{page_obj.next_page_number}}" aria-label="Next page">Next</a></li>
            {% endif %}
          </ul>
          {% endif %}
        </nav>
  
      </div>
  
    </div>
  </div>
  {% endblock content %}

templates/departamento/new_departamento.html
{% extends 'base.html' %}
{% load static%}
{% block title %} Sistema Empleado | Inicio {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}

<h1>Registar Departamento</h1>
<form method="post">{% csrf_token %}

    <h3>Datos del Empleado</h3>
    <p>{{ form.nombre }}</p>
    <P>{{ form.apellidos }}</P>

    <h3>Datos del Departamento</h3>
    <p>{{ form.departamento }}</p>
    <P>{{ form.shorname }}</P>


    <input type="submit" value="Save">
</form>
{% endblock content %}