app/personas/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'personas_app'
urlpatterns = [
  
    path('listar-all-personas/', views.ListAllPersonas.as_view(),name ='all-personas'),
    path('list-by-area/<area>/', views.ListByAreaPersonas.as_view(),name ='list-by-area'),
    path('find-personas/', views.ListPersonasByKeyword.as_view(),name ='find-personas'),
    path('habilidades/', views.ListHabilidades.as_view()),
    path('ver-detail/<pk>/', views.PersonasDetailView.as_view(),name='ver-detail'),
    path('add-personas/', views.PersonasCreateView.as_view(),name='add-personas'),
    path('success/', views.SuccesView.as_view(),name='success'),
    path('update-personas/<pk>/', views.PersonasUpdateView.as_view(),name='update-personas'),
    path('delete-personas/<pk>/', views.PersonasDeleteView.as_view(),name='delete-personas'),
    
   
 ]

empleados/urls.py
"""empleados URL Configuration

"""
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('',include('app.departamento.urls')),
    re_path('',include('app.personas.urls')),
    re_path('',include('app.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/personas/models.py
from distutils.command.upload import upload
from enum import unique
from django.db import models

from app.departamento.models import Departamento
from ckeditor.fields import RichTextField

class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)

    class Meta:
        verbose_name= 'Habilidad'
        verbose_name_plural='Habilidad Personas'
      

    def __str__(self):
        return str(self.id) + '-' + self.habilidad 

# Create your models here.
class Personas(models.Model):

    JOB_CHOICES = (
        ('0', 'CONTADOR'),
        ('1', 'ADMINISTRADOR'),
        ('2', 'ECONOMISTA'),
        ('3', 'ASISTENTE'),

    )
    class Meta:
        verbose_name= 'Personas'
        verbose_name_plural='Persona'
        ordering = ['name']
        unique_together =('name','correo')

    name = models.CharField('Nombre',max_length=100)
    last_name = models.CharField('Apellido',max_length=100, null=True, blank=True)
    full_name = models.CharField('Nombre Completo',max_length=200, blank=True, null=True)
    #departamento = models.OneToOneField(Departamento, null=True, blank=True, on_delete=models.CASCADE)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    fec_nac = models.DateTimeField('Fecha_Nac',blank=True, null=True)
    direccion = models.CharField('Direccion', max_length=200, null=True, blank=True)
    correo = models.EmailField('Correo',blank=True)
    job = models.CharField('Cargos', max_length=1, choices=JOB_CHOICES)
    salario = models.DecimalField('salario', max_digits=10, decimal_places=2)
    habilidades = models.ManyToManyField(Habilidades,blank=True)
    cv = RichTextField()
    avatar = models.ImageField(upload_to='personas', null=True, blank=True)

    def __str__(self):
        return str(self.id) + '-' + self.name 

app/personas/forms.py
from django import forms
from .models import Personas

from ckeditor.widgets import CKEditorWidget

class PersonasForm(forms.ModelForm):

    class Meta:
        model = Personas
        fields = (
            'name', 'last_name', 'correo', 'fec_nac', 'direccion',
              'departamento', 'job', 'habilidades', 'salario','full_name','cv','avatar',
        )

        widgets = { 
            'habilidades': forms.CheckboxSelectMultiple(),
            'cv': forms.CharField(widget=CKEditorWidget(config_name='awesome_ckeditor'))
            

        }

app/personas/views.py
from django.utils import timezone
from re import template
from django.urls import reverse_lazy
from django.shortcuts import render
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView,
)

from .models import Personas

from .forms import PersonasForm


class ListAllPersonas(ListView):
    template_name = 'personas/list_all.html'
    #model = Personas
    paginate_by = 4
    ordering = ('full_name',)

    def get_queryset(self):
        palabra_clave = self.request.GET.get('kword', '')
        lista = Personas.objects.filter(
            full_name__icontains=palabra_clave
        )
        return lista


class ListByAreaPersonas(ListView):
    template_name = 'personas/list_by_area.html'
    paginate_by = 5
    ordering = ('name',)

    def get_queryset(self):
        area = self.kwargs['area']
        lista = Personas.objects.filter(
            departamento__shor_name=area
        )
        return lista

# recuperar desde caja de texto


class ListPersonasByKeyword(ListView):
    template_name = 'personas/list_by_keyword.html'
    context_object_name = 'personas'
    paginate_by = 5
    ordering = ('name',)

    def get_queryset(self):
        area = self.request.GET.get('kword', '')
        lista = Personas.objects.filter(
            departamento__shor_name=area
        )
        return lista


class ListHabilidades(ListView):
    template_name = 'personas/list_habilidades.html'
    context_object_name = 'habilidades'

    def get_queryset(self):

        idtext = self.request.GET.get('id', '')
        if idtext == '' or idtext == '0':
            id = 0
            return []
        else:
            id = int(idtext)
            persona = Personas.objects.get(id=id)
            return persona.habilidades.all()


class PersonasDetailView(DetailView):
    model = Personas
    template_name = "personas/detail.html"
    context_object_name = 'persona'
    success_url = reverse_lazy('personas_app:all-personas')
    def get_context_data(self, **kwargs):
        context = super(PersonasDetailView, self).get_context_data(**kwargs)
        context['titulo'] = 'Detalle de Personas'
        return context


class SuccesView(TemplateView):
    template_name = "personas/success.html"


class PersonasCreateView(CreateView):
    
    template_name = "personas/create.html"
    model = Personas
    form_class = PersonasForm
    
    #fields =('__all__')
    success_url = reverse_lazy('personas_app:all-personas')

    def form_valid(self, form):

        persona = form.save(commit=False)
        persona.full_name = persona.name + ' ' + persona.last_name
        persona.save()
        return super(PersonasCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(PersonasCreateView, self).get_context_data(**kwargs)
        context['titulo'] = 'Crear Personas'
        return context


class PersonasUpdateView(UpdateView):
    model = Personas
    template_name = "personas/update.html"
    fields = ['name', 'last_name', 'correo', 'fec_nac', 'direccion',
              'departamento', 'job', 'habilidades', 'salario','full_name','cv','avatar']
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('personas_app:all-personas')

    def post(self, request, *args, **kwargs):

        self.object = self.get_object()

        print(request.POST['name'] + ' ' + request.POST['name'])
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):

        persona = form.save(commit=False)
        persona.full_name = persona.name + ' ' + persona.last_name
        persona.save()
        return super(PersonasUpdateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(PersonasUpdateView, self).get_context_data(**kwargs)
        context['titulo'] = 'Update Personas'
        return context


class PersonasDeleteView(DeleteView):
    model = Personas
    template_name = "personas/delete.html"
    success_url = reverse_lazy('personas_app:all-personas')

    def get_context_data(self, **kwargs):
        context = super(PersonasDeleteView, self).get_context_data(**kwargs)
        context['titulo'] = 'Delete Personas'
        return context

templates/personas/create.html
{% extends 'base.html' %}
{% load static%}
{% block title %} Sistema Empleado | Incluir {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}


<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell"> {{ titulo }} </h1>
    </div>
    <div class="grid-x">
        
        <form class="cell grid-x grid-margin-x" method="post" enctype="multipart/form-data">{% csrf_token %}
            <div class="medium-6 cell">
                <label>Nombre:
                    {{ form.name }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellido:
                    {{ form.last_name }}
                  
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Direccion:
                    {{ form.direccion }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Correo Electronico:
                   {{ form.correo}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Departamento:
                    {{ form.departamento}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Cargo:
                    {{ form.job}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Habilidades:
                   {{ form.habilidades}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Resumen Curricular:
                   {{ form.cv}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Fecha de Ingreso:
                   {{ form.fec_nac}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Salario:
                   {{ form.salario}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Foto de Perfil:
                   {{ form.avatar}}
                </label>
            </div>

            
            
            <div class="medium-6 cell">
                <input type="submit" class="button success" value="Crear">
            </div>
           
        </form>
    </div>
    {% endblock content%}

templates/personas/delete.html
{% extends 'base.html' %}
{% load static%}
{% block title %} Sistema Empleado | Delete {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell"> {{ titulo }}   {{ object.full_name }} </h1>
    </div>
    <div class="grid-x">
    <form class="cell grid-x grid-margin-x"method="post" enctype="multipart/form-data">{% csrf_token %}
   
        
        <div class="large-10 cell">
            <div class="callout secondary">
                <h5>Desea Eliminar este empleado ?</h5>
                <p>Recuerde que es una operacion irreversible.</p>
                <input class="alert button" type="submit" value="Delete">
              </div>
        </div>
    
     

</form>
</div>
</div>

{% endblock content%}

templates/personas/detail.html
{% extends 'base.html' %}
{% load static%}
{% block title %} Sistema Empleado | Detalle Empleados {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x grid-padding-x"">
      <h1 class=" cell">{{ object.full_name }}</h1>
      <form class="cell grid-x grid-margin-x">
        <div class="medium-12 cell"> 
        <div class="card" style="width: 150px;">
        
            {% if persona.avatar %}
               <img src="{{ persona.avatar.url }}"> 
            {% else %}
                <img src="{% static 'img/noavatar.jpg' %}"> 
            {% endif %}
      
        </div>
        </div>
        <div class="medium-6 cell">
            <label>Nombre:
               <input type="text" placeholder=".medium-6.cell" value= "{{ persona.name }}"> 
            </label>
        </div>
        <div class="medium-6 cell">
            <label>Apellido:
                <input type="text" placeholder=".medium-6.cell" value= "{{ persona.last_name }}"> 
              
            </label>
        </div>
        <div class="medium-6 cell">
            <label>Direccion:
              <input type="text" placeholder=".medium-6.cell" value= "{{ persona.direccion }}"> 
            </label>
        </div>
        <div class="medium-6 cell">
            <label>Correo Electronico:
               <input type="text" placeholder=".medium-6.cell" value= "{{ persona.correo }}"> 
            </label>
        </div>
        <div class="medium-6 cell">
            <label>Departamento:
                <input type="text" placeholder=".medium-6.cell" value= "{{ persona.departamento.shor_name }}"> 
            </label>
        </div>
        <div class="medium-6 cell">
            <label>Cargo:
                <input type="text" placeholder=".medium-6.cell" value= "{{ persona.get_job_display }}"> 
            </label>
        </div>
        <div class="medium-6 cell">
            <label>Habilidades:</label>
             <ul class="vertical menu">
                {% for h in persona.habilidades.all %}
                    <li>{{ h.habilidad }}</li>
                {% endfor %}
              
             </ul>
        </div>
        <div class="medium-6 cell">
            <label>Resumen Curricular:
            <input type="text" placeholder=".medium-6.cell" value= "{{ persona.cv }}">    
            </label>
        </div>
        <div class="medium-6 cell">
            <label>Fecha de Ingreso:
               <input type="text" placeholder=".medium-6.cell" value= "{{ persona.fec_nac }}"> 
            </label>
        </div>
         <div class="medium-6 cell">
            <label>Salairo:
                <input type="text" placeholder=".medium-6.cell" value= "{{ persona.salario }}"> 
            </label>
        </div>
        

       

        
        <div class="medium-6 cell">
          
             <input class="alert button" type="submit" value="Regresar">
        </div>
       
    </form>
    </div>
</div>
{% endblock content %}

templates/personas/list_all.html
{% extends 'base.html' %}
{% load static%}
{% block title %} Sistema Empleado | Inicio {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}


<div class="grid-container">
  <div class="grid-x">
    <h1 class="cell">All Employes</h1>
    <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
      <div class="cell large-7">
        <input type="search" id="kword" name="kword" placeholder="Buscar Empleado">
      </div>

      <div class="cell large-2">
        <button type="submit" class="button">Buscar</button>
      </div>
    </form>


    <div class="cell grid-x">
      <table>
        <thead>
          <tr>
            <th width="200">Nombre Empleado</th>
            <th width="200">Correo</th>
            <th width="150">Cargo</th>
            <th width="200">Departamento</th>
            <th width="300">Accion</th>
          </tr>
        </thead>
        <tbody>
          {% for empleados in object_list %}
          <tr>
            <td>{{ empleados.full_name }} </td>
            <td>{{ empleados.correo }} </td>
            <td>{{ empleados.job }} </td>
            <td>{{ empleados.departamento }} </td>
            <td>
              <a class="warning success button" href="{% url 'personas_app:ver-detail' empleados.id %}" {>Ver</a> 
              <a class="submit success button" href="{% url 'personas_app:update-personas' empleados.id %}" {>Edit</a> 
              <a class="alert button" href="{% url 'personas_app:delete-personas' empleados.id %}" {>Delete</a>
            </td>
          </tr>
          {% empty %}
          <li>No empleados yet.</li>
          {% endfor %}
        </tbody>
      </table>



    </div>
    <div class="cell">
      {% if is_paginated %}

      <nav aria-label="Pagination">
        <ul class="pagination text-center">
          {% if page_obj.has_previous %}
          <li class="pagination-previous"><a href="?page={{page_obj.previous_page_number}}"
              aria-label="Next page">Previous</a></li>
          {% endif %}

          {% for pagina in paginator.page_range %}
          {% if page_obj.number == pagina %}

          <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }}</li>

          {% else %}

          <li><a href="?page={{pagina}}" aria-label="Page 2">{{ pagina }}</a></li>
          {% endif %}
          {% endfor %}

          {% if page_obj.has_next %}
          <li class="pagination-next"><a href="?page={{page_obj.next_page_number}}" aria-label="Next page">Next</a></li>
          {% endif %}
        </ul>
        {% endif %}
      </nav>

    </div>

  </div>
</div>
{% endblock content %}

templates/personas/list_by_area.html
{% extends 'base.html' %}
{% load static%}
{% block title %} Sistema Empleado | Empleados por Departamento {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}


<div class="grid-container">
    <div class="grid-x">
      <h1 class="cell">Empleados del Departamento: {{ object_list.departamento }}</h1>
    
  
  
      <div class="cell grid-x">
        <table>
          <thead>
            <tr>
              <th width="200">Nombre</th>
              <th width="200">Correo</th>
              <th width="150">Cargo</th>
            
            </tr>
          </thead>
          <tbody>
            {% for e in object_list %}
            <tr>
              <td>{{ e.full_name }} </td>
              <td>{{ e.correo}} </td>
              <td>{{ e.job}} </td>
              
            </tr>
            {% empty %}
            <li>No empleados yet.</li>
            {% endfor %}
          </tbody>
        </table>
  
  
  
      </div>
      <div class="cell">
        {% if is_paginated %}
  
        <nav aria-label="Pagination">
          <ul class="pagination text-center">
            {% if page_obj.has_previous %}
            <li class="pagination-previous"><a href="?page={{page_obj.previous_page_number}}"
                aria-label="Next page">Previous</a></li>
            {% endif %}
  
            {% for pagina in paginator.page_range %}
            {% if page_obj.number == pagina %}
  
            <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }}</li>
  
            {% else %}
  
            <li><a href="?page={{pagina}}" aria-label="Page 2">{{ pagina }}</a></li>
            {% endif %}
            {% endfor %}
  
            {% if page_obj.has_next %}
            <li class="pagination-next"><a href="?page={{page_obj.next_page_number}}" aria-label="Next page">Next</a></li>
            {% endif %}
          </ul>
          {% endif %}
        </nav>
  
      </div>
  
    </div>
  </div>
  {% endblock content %}

templates/personas/list_by_keyword.html
{% extends 'base.html' %}
{% load static%}
{% block title %} Sistema Empleado | Inicio {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}


<div class= "grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista de Empleados por Area</h1>

<form method="GET">{% csrf_token %}
        <div class="cell grid-x grid-margin-x">
            <div class="cell large-7">
               <input type="text" id="kword" name="kword" placeholder="Ingrese el Area">            
            </div>
            
            <div class="cell large-2">
                <button type="submit" class="button">Buscar</button>
            </div>
       </div>

       <ul>
        {% for persona in personas %}
            <li>{{ persona.departamento}} - {{ persona.name }}</li>
        {% empty %}
            <li>No personas yet.</li>
        {% endfor %}
        </ul>
        
        </div>
    

</form>



{% endblock content %}

templates/personas/list_habilidades.html
<h1>Employes by Areas KeyWord</h1>
<form method="GET">{% csrf_token %}
    <input type="number" id="id" name="id" value="0" placeholder="Ingrese Id Empleado">
    <button type="submit">Buscar</button>

</form>

<h3>Lista de Habiliades por Empleado</h3>
<ul>
{% for persona in habilidades %}
    <li>{{ persona.id}} - {{ persona.habilidad }}</li>
{% empty %}
    <li>No personas yet.</li>
{% endfor %}
</ul>

templates/personas/success.html
{% extends 'base.html' %}
{% load static%}
{% block title %} Sistema Empleado | Delete {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}

<h1>Registro de usuarios satisfactorio</h1>
<p>
    <a href="#0">Regresar al listado de personas</a>
</p>
{% endblock content %}

templates/personas/update.html
{% extends 'base.html' %}
{% load static%}
{% block title %} Sistema Empleado | Update {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}


<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell"> {{ titulo }} </h1>
    </div>
    <div class="grid-x">
        
        <form class="cell grid-x grid-margin-x" method="post" enctype="multipart/form-data">{% csrf_token %}
            <div class="medium-6 cell">
                <label>Nombre:
                    {{ form.name }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellido:
                    {{ form.last_name }}
                  
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Direccion:
                    {{ form.direccion }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Correo Electronico:
                   {{ form.correo}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Departamento:
                    {{ form.departamento}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Cargo:
                    {{ form.job}}
                </label>
            </div>
            <div class="large-12 cell">
                <label>Habilidades:
                   {{ form.habilidades}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Fecha de Ingreso:
                   {{ form.fec_nac}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Salario:
                   {{ form.salario}}
                </label>
            </div>
            <div class="large-12 cell">
                <label>Resumen Curricular:
                   {{ form.cv}}
                </label>
            </div>
            <div class="large-12 cell">
                <label>Foto de Perfil:
                   {{ form.avatar}}
                </label>
            </div>

            <div class="medium-6 cell">
                <input type="submit" class="button" value="Actualizar">
            </div>
           
        </form>
    </div>
    {% endblock content%}